#This file is supposed to be processed by Maven, but Android doesn't run Maven
#So in Android we've filled in the resulting values below
VERSION=0.8.15-SNAPSHOT.android
COMMITID=56ee20ac243c01059d8d69783e1e94f21071e20c
HOMEURL=http://www.jacoco.org/jacoco
RUNTIMEPACKAGE=org.jacoco.agent.rt.internal
